#! /usr/bin/env bash

mkdir build
cd build

rm CMakeCache.txt
echo deleting CMakeCache.txt...

CXXFLAGS="-std=c++11" \
CXX=g++ \
CC=gcc \
cmake \
  -DSST_CORE=$HOME/Programs/install/sstcore-7.1.0 \
  -DPIN_ROOT=$HOME/Programs/pin-3.2-81205-clang-mac \
..
