#! /usr/bin/env bash

echo moving to the build directory...
cd build

rm CMakeCache.txt
echo deleting CMakeCache.txt...

INSTALL_PATH=$HOME/Desktop/workflowProject_copy2_install

CXXFLAGS="-std=c++11" \
CXX=g++ \
CC=gcc \
cmake \
  -DMY_SST_CORE=$HOME/Desktop/workflowProject_copy2/include \
  -DSST_CORE=$HOME/Programs/install/sstcore-7.1.0 \
  -DPIN_ROOT=$HOME/Programs/pin-3.2-81205-clang-mac \
  -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH \
..
